### ISSUE TITLE
Share and bookmark links are crazy long

### ISSUE THREAD

**Issue by abpoloc** [LibraryOfCongress/viewshare#107]
anyway to make them less ugly?

**Comment by ptrourke** [comment]
The share and bookmark links are using a standard [UUID](http://en.wikipedia.org/wiki/Universally_unique_identifier)

The length and randomness of the UUID provide some privacy for shared "private" views (it's really unlikely that someone could guess the valid UUID for a Viewshare link).

**Comment by dfeeney** [comment]
I used this function recently in another project to shorten UUID's. It'll take it down to 22 characters or less. I think you can just drop this into the slug generation for future shares, and the existing ones will still use the long UUID's.

```
def base57(num):
    """
    Converts an integer into a string representation in base 57.
    Uses all alphanumerical characters that aren't visually ambiguous.
    (ie, not one of 0,O,1,l,I).

    Derived from http://code.activestate.com/recipes/65212-convert-from-decimal-to-any-base-number/#c5
    and the idea for excluding those 5 characters from `shortuuid`

    :param num:
    :return:
    """
    b = 57
    numerals = "23456789abcdefghijkmnopqrstuvwxyzABCDEFGHJKLMNPQRSTUVWXYZ"

    return (((num == 0) and numerals[0]) or
            (base57(num // b).lstrip(numerals[0]) + numerals[num % b]))

```

**Comment by ptrourke** [comment]
Clever. I think you've got a good idea here, and I'll branch and add.
