### ISSUE TITLE
Not allowing save or preview of views for certain data sets

### ISSUE THREAD

**Issue by etobey** [LibraryOfCongress/viewshare#113]
This is an addendum to issue #111. I was trying to create views of the DP14 conference attendee data in the Beta version. Although I was able to get the map view to work, when I tried the pie chart, bar graph, and other views, I was unable to preview or save the views. I have a screenshot attached as an example of what happens.
![betapiechart](https://cloud.githubusercontent.com/assets/7976276/3615543/c1438c20-0dc9-11e4-8d9b-fee6956e22f1.jpg)

**Comment by ptrourke** [comment]
Merged with #162 

Ref. Uservoice tickets 99, 105, 106, 109, from D. M. Alexander, @tjowens, B. Kroege, and S. Bender, respectively.

**Comment by tjowens** [comment]
Not sure if this helps or not, but I was able to see the rest of the views part on one only after I converted the original file I was working from to .xls. So I'm not sure if there is some strange artifact or something that is left in the data when you upload .xlsx that is hanging something in the view building process.

**Comment by ptrourke** [comment]
Thanks! That seems a lot like what I’ve seen.

PTR

**Comment by ptrourke** [comment]
Might finally have a handle on this.

Deleting columns in the exhibit Edit pane causes a mismatch between the items in the view and the items in the underlying exhibit. For example, if you have a dataset with 7 columns, and you delete 2 of them, like this:

`[0, 1, 2, 3, 4, 5, 6] -> [_, 1, 2, 3, _, 5, 6]`

multiselect.js throws a "can't getID from null" error when it iterates through 1 and 4 (at l. 179). This prevents the multiselect from being rendered.

**Comment by ptrourke** [comment]
Not sure the relationship between this issue and #162 . Unmerged #162 for now.
