### ISSUE TITLE
Links intermittently not working in embedded views

### ISSUE THREAD

**Issue by ptrourke** [LibraryOfCongress/viewshare#158]
In embedded views, the links intermittently fail to work.

In Chrome debugger and Firefox Developer edition, get a "Uncaught TypeError: cannot read property 'data' of null" error on [this line of _history.js_](https://github.com/LibraryOfCongress/viewshare/blob/master/viewshare/apps/exhibit/static/simile/exhibit/scripts/util/history.js#L186):

```
EHistory.pushComponentState = function(component, registry, data, subtitle, lengthy) {
   var state = EHistory.getState();
   EHistory.setComponentState(state, component, registry, data, lengthy);
   EHistory.pushState(state.data, subtitle);    # Line 186
};
```

It looks like the **EHistory** [is not enabled](https://github.com/LibraryOfCongress/viewshare/blob/master/viewshare/apps/exhibit/static/simile/exhibit/scripts/util/history.js#L141), so that the state is null:

```
EHistory.getState = function() {
    if (EHistory.enabled) {
        return History.getState();
    } else {
       return null; # Line 141 
    }
};
```

The only place **EHistory** is enabled [is in _history-init.js_](https://github.com/LibraryOfCongress/viewshare/blob/master/viewshare/apps/exhibit/static/simile/exhibit/scripts/util/history-init.js#L17):

```
EHistory.init = function(ex, persist) {
    var state, types, i, j, keys, component;
    if (typeof History !== "undefined" && History.enabled) {
        EHistory.enabled = true; # Line 17
        EHistory._originalTitle = document.title;
        EHistory._originalLocation = Persistence.getURLWithoutQueryAndHash();
        EHistory._registry = ex.getRegistry();
[....]
```

When I put a breakpoint in at line 17 and the breakpoint is hit, the links work. When the breakpoint is not hit, is does not work. It looks to me as though line 186 of _history.js_ script is sometimes being called before line 17 of _history-init.js_ - which would prevent the EHistory from being enabled, and so we get the null 

[EDIT: _When it is run on-demand,_ ] RequireJS loads scripts asynchronously. My guess is that we need to make sure that _history-init.js_ loads and `EHistory.init` fires before `EHistory.pushComponentState` fires. This might be problematic because _history.js_ is a dependency of _history-init.js_.

[RequireJS incorrectly loads scripts from URLs](http://stackoverflow.com/questions/22874664/requirejs-incorrectly-loads-scripts-from-urls)

**Comment by ptrourke** [comment]
Fixed issue with collectstatic, but still seeing this behavior at times. Also seeing certain images appearing with `undefinedimages/[...]` URLs instead of `viewshare.org/images/[...]` URLs. These two issues occur only simultaneously, so are probably symptoms of the same issue.

**Comment by ptrourke** [comment]
The images that are showing `undefinedimages/` URLs are being generated in `ui.js`, e.g., 

    UIUtilities.createTranslucentImageHTML = function(relativeUrl, verticalAlign) {
        return $.simileBubble("createTranslucentImageHTML", Exhibit.urlPrefix + relativeUrl, verticalAlign);
    };

When the bug manifests, `Exhibit.urlPrefix` is undefined (the default value), so the URLs are rendered as `[local url]/undefinedimages/no-check-no-border.png` rather than `http://viewshare.org/static/simile/exhibit/images/no-check-no-border.png` . 

The attribute `Exhibit.urlPrefix` is defined in `exhibit-base.js`, with a value of *undefined*; it is assigned a value in `exhibit.js` in the `Exhibit.setup` function, where it obtains the value from either the module configuration or from one of two scripts on the page, `exhibit-api.js` or `exhibit-bundle.js`. For embeds, the module configuration is defined in embed-main.js inside the requirejs.config() call.

**Comment by ptrourke** [comment]
Have taken another angle on this with the requirejs.config object.

As it is now, the requirejs `config` used for embedded views is being generated in a Django template `show.js` that then calls require.js and `embed-main.js` with a standard require call. The `show.js` (which is the superstructure of the `embed.js` file that is sent to the client) in calling `embed-main.js` is calling un-optimized files; the config has module prefixes that are assembled using django variables pointing to viewshare.org to make sure they are loaded by embed-main from the viewshare.org site rather than the site embedding the view.

The config also has a path listing for jquery, shims for both 'jquery' and 'lib/jquery' and a mapping of 'lib/jquery' to 'jquery'. However, the RequireJS documentation notes that `map` does not work well with non-AMD modules (like jquery).

**Comment by ptrourke** [comment]
[@dfeeney] suggests that calling `Exhibit.setup` via `$(document).ready(Exhibit.setup)` may be causing Exhibit.setup to wait until the exhibit has been rendered. 

He suggested calling Exhibit.setup directly before the initialize() call in *-main.js, but this doesn't load at all. Right now, have simple removed the .ready condition from the call, so that it is called when it is reached, regardless of whether the DOM has stopped rendering. So far, that seems to be working.

**Comment by ptrourke** [comment]
Specifically, am reminded of this. https://github.com/LibraryOfCongress/viewshare/issues/63#issuecomment-36083938 .

**Comment by dfeeney** [comment]
Hi @ptrourke, I don't see the issues/158/require_ready branch. I don't think issue #63 is related, as that just has to do with hooking into a second jquery instance. Everything in the embed, display and editor pages should be going through require.js already.

I'm still pretty sure this has to do with the use of $(document).ready. There are 4 places where it's being used to initialize exhibit components. Once in exhibit.js, and once for each of the map, timeline and flot extensions. In the case of the display and editor components, it's going to defer the execution of those methods until the page and scripts have been properly loaded. It does this by waiting for the DOM load event. They are still going to be executed asynchronously in the event loop, however.

In the case of embedding, the DOM load event has already fired by the time they are registered with the ready handler, so the ready handlers might be executed at any time.

I think the solution might be to depend on two separate events for registration, perhaps managed through the jquery promise mechanism. One, of course, would be the ready event. The second would be a custom event that would have to be explicitly fired at some point in the outer loop of the load process.
