### ISSUE TITLE
Finish conversion of scripts over to require.js and migration to jquery  in freemix/js/lib

### ISSUE THREAD

**Issue by dfeeney** [LibraryOfCongress/viewshare#63]
In the exhibit_display page, some scripts (particularly detail.js and share_dialog.js) depend on the jquery script (1.7) that's loaded in the base template, which is then replaced by jquery 1.10 when it's loaded asynchronously.

I think the right approach here is to convert the share_dialog.js and detail.js scripts that are loaded by the exhibit display script over to require.js. After looking into it, it looks like the exhibit_detail templates also load these, so we'd probably want to convert that over to r.js as well.

More generally, we might want to replace the scripts that are loaded in base_scripts with a require main that ensures that jquery and bootstrap are loaded.  We might then be able to do away with the distinction between the 'base_scripts' and 'extra_scripts' blocks in the templates.  At a cursory glance, the task of converting everything over to this scheme doesn't look to onerous, but there is a good deal of busy work there.  At the very least, the base template should load the jquery version in freemix/js/lib, and anything that breaks fixed.  @zepheiryan pointed out in #62 that this breaks compatible.js.  I wonder if we can do away with that?

**Comment by ptrourke** [comment]
Believe that #158 is related to actions in this issue and #69.
